In [1]:
# =========================================================
# SmartChat Insight
# Análisis de los datos, clientes (recurrentes, perdidos) y productos
# =========================================================

# Importar librerías
import re
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

# Definir rutas
clean_path = Path("../data/cleaned/whatsapp_clean.csv")
output_path = Path("../data/outputs/")
output_path.mkdir(parents=True, exist_ok=True)

# Cargar datos limpios
df = pd.read_csv(clean_path)
df["date"] = pd.to_datetime(df["date"], errors="coerce")

print("Datos cargados correctamente")
print(f"Total de mensajes: {len(df)}")
df.head(5)

Datos cargados correctamente
Total de mensajes: 44993

,date,time,user,message,file_name
0,2025-10-25,12:47 p. m.,+1 (772) 800-8661,Hola!,Chat de WhatsApp con +1 (772) 800-8661.txt
1,2025-10-25,12:47 p. m.,Vidrios Y Fachadas,"Bienvenido, conoce nuestra variedad de productos:",Chat de WhatsApp con +1 (772) 800-8661.txt
2,2025-10-25,12:47 p. m.,+1 (772) 800-8661,Estoy buscando ventanas corredizas en aluminio...,Chat de WhatsApp con +1 (772) 800-8661.txt
3,2025-10-25,3:00 p. m.,Vidrios Y Fachadas,Si señor,Chat de WhatsApp con +1 (772) 800-8661.txt
4,2025-10-25,3:00 p. m.,Vidrios Y Fachadas,Se las tenemos,Chat de WhatsApp con +1 (772) 800-8661.txt

In [2]:
# Pasar todo a minúsculas
df["clean_message"] = df["message"].str.lower()

# Eliminar puntuación básica
df["clean_message"] = df["clean_message"].apply(lambda x: re.sub(r"[^a-záéíóúüñ0-9\s]", "", x))

In [3]:
def remove_emojis(text):
    return re.sub(r"[^\w\s.,!?áéíóúüñÁÉÍÓÚÜÑ]", "", str(text))

In [4]:
df["message"] = df["message"].apply(remove_emojis)

In [5]:
df

,date,time,user,message,file_name,clean_message
0,2025-10-25,12:47 p. m.,+1 (772) 800-8661,Hola!,Chat de WhatsApp con +1 (772) 800-8661.txt,hola
1,2025-10-25,12:47 p. m.,Vidrios Y Fachadas,"Bienvenido, conoce nuestra variedad de productos",Chat de WhatsApp con +1 (772) 800-8661.txt,bienvenido conoce nuestra variedad de productos
2,2025-10-25,12:47 p. m.,+1 (772) 800-8661,Estoy buscando ventanas corredizas en aluminio...,Chat de WhatsApp con +1 (772) 800-8661.txt,estoy buscando ventanas corredizas en aluminio...
3,2025-10-25,3:00 p. m.,Vidrios Y Fachadas,Si señor,Chat de WhatsApp con +1 (772) 800-8661.txt,si señor
4,2025-10-25,3:00 p. m.,Vidrios Y Fachadas,Se las tenemos,Chat de WhatsApp con +1 (772) 800-8661.txt,se las tenemos
...,...,...,...,...,...,...
44988,2025-02-12,3:54 p. m.,💫Zenia Saory💫,Ok..lo solicitó,Chat de WhatsApp con 💫Zenia Saory💫.txt,oklo solicitó
44989,2025-02-12,3:55 p. m.,Vidrios Y Fachadas,mil gracias,Chat de WhatsApp con 💫Zenia Saory💫.txt,mil gracias
44990,2025-09-17,8:40 p. m.,💫Zenia Saory💫,Buena tarde..,Chat de WhatsApp con 💫Zenia Saory💫.txt,buena tarde
44991,2025-09-17,8:41 p. m.,Vidrios Y Fachadas,"Bienvenido, conoce nuestra variedad de productos",Chat de WhatsApp con 💫Zenia Saory💫.txt,bienvenido conoce nuestra variedad de productos
44992,2025-09-17,8:41 p. m.,Vidrios Y Fachadas,En este momento nuestro grupo de asesores se e...,Chat de WhatsApp con 💫Zenia Saory💫.txt,en este momento nuestro grupo de asesores se e...

In [ ]:
from collections import Counter
import nltk
from nltk.corpus import stopwords


nltk.download("stopwords")
stopwords_es = set(stopwords.words("spanish"))

# Dividir en palabras y eliminar stopwords
all_words = [
    word for msg in df["clean_message"].dropna()
    for word in msg.split()
    if word not in stopwords_es and len(word) > 2
]

# Contar palabras más comunes
word_counts = Counter(all_words)
pd.DataFrame(word_counts.most_common(30), columns=["word", "count"])

ModuleNotFoundError: No module named 'nltk'

In [ ]:
import nltk
from nltk.corpus import stopwords

print("Total stopwords:", len(stopwords.words("spanish")))

ModuleNotFoundError: No module named 'nltk'